# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.13

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
    deploy-job:
      steps:
        - add_ssh_keys:
            fingerprints:
              - "99:1c:2a:31:45:3e:49:04:39:e0:89:e0:5e:c4:72:9f"
    deploy:
      steps:
        - run:
            name: Deploy to GCP for SSH
            command: |
              ssh $SSH_USER@$SSH_HOST 'bash -s < ../scripts/deploy.sh'
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
